apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: crds-finance
  namespace: api
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 0 
  template: 
    metadata: 
      labels: 
        app: crds-finance
    spec: 
      containers: 
        - name: crds-finance
          image: crdschurch/crds-service-finance:$DOCKER_TAG 
          imagePullPolicy: Always 
          ports: 
            - containerPort: 80 
          resources: 
            limits: 
              memory: "2Gi"
              cpu: "700m" 
            requests: 
              memory: "16Mi" 
              cpu: "100m" 
          readinessProbe:
            httpGet:
              path: /api/health/status
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health/status
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          env: 
            - name: APP_LOG_ROOT
              value: $APP_LOG_ROOT
            - name: ASPNETCORE_ENVIRONMENT
              value: $ASPNETCORE_ENVIRONMENT
            - name: CRDS_MP_COMMON_CLIENT_ID
              value: $CRDS_MP_COMMON_CLIENT_ID
            - name: CRDS_MP_COMMON_CLIENT_SECRET
              value: $CRDS_MP_COMMON_CLIENT_SECRET
            - name: CRDS_GATEWAY_CLIENT_ENDPOINT
              value: $CRDS_GATEWAY_CLIENT_ENDPOINT
            - name: HANGFIRE_URL
              value: $HANGFIRE_URL
            - name: MP_OAUTH_BASE_URL
              value: $MP_OAUTH_BASE_URL
            - name: MP_REST_API_ENDPOINT
              value: $MP_REST_API_ENDPOINT
            - name: PUSHPAY_API_ENDPOINT
              value: $PUSHPAY_API_ENDPOINT
            - name: PUSHPAY_AUTH_ENDPOINT
              value: $PUSHPAY_AUTH_ENDPOINT
            - name: PUSHPAY_WEB_ENDPOINT
              value: $PUSHPAY_WEB_ENDPOINT
            - name: PUSHPAY_CLIENT_ID
              value: $PUSHPAY_CLIENT_ID
            - name: PUSHPAY_CLIENT_SECRET
              value: $PUSHPAY_CLIENT_SECRET
            - name: PUSHPAY_MERCHANT_KEY            
              value: $PUSHPAY_MERCHANT_KEY
            - name: NEW_RELIC_LICENSE_KEY            
              value: $NR_INSTALL_KEY
            - name: NEW_RELIC_APP_NAME
              value: $NR_APP_NAME