apiVersion: v1 
kind: Service 
metadata: 
  name: crds-service-finance
  namespace: api
  labels: 
    app: crds-service-finance
spec: 
  ports: 
  - name: dotnet 
    port: 80
    targetPort: 80 
  selector: 
    app: crds-service-finance