apiVersion: v1 
kind: Service 
metadata: 
  name: crds-service-finance
  labels: 
    app: crds-service-finance
spec: 
  ports: 
  - name: dotnet 
    port: 80 
    targetPort: 5050 
  selector: 
    app: crds-service-finance