version: '3' 
services: 
  CrossroadsServiceFinance: 
    build: 
      context: ../../ 
      dockerfile: ./deployment/docker/prod.Dockerfile
    container_name: crds-service-finance
    image: crdschurch/crds-service-finance:${DOCKER_TAG:-local} 
    env_file:
      - ../../.env
    ports:
      - "5000:80"
    environment: 
      - APP_LOG_ROOT=${APP_LOG_ROOT}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CRDS_ENV=${CRDS_ENV}
      - CRDS_MP_COMMON_CLIENT_ID=${CRDS_MP_COMMON_CLIENT_ID}
      - CRDS_MP_COMMON_CLIENT_SECRET=${CRDS_MP_COMMON_CLIENT_SECRET}
      - MP_API_DB_USER=${MP_API_DB_USER}
      - MP_API_DB_PASSWORD=${MP_API_DB_PASSWORD}
      - MP_OAUTH_BASE_URL=${MP_OAUTH_BASE_URL}
      - MP_REST_API_ENDPOINT=${MP_REST_API_ENDPOINT}
      - PUSHPAY_API_ENDPOINT=${PUSHPAY_API_ENDPOINT}
      - PUSHPAY_AUTH_ENDPOINT=${PUSHPAY_AUTH_ENDPOINT}
      - PUSHPAY_WEB_ENDPOINT=${PUSHPAY_WEB_ENDPOINT}
      - PUSHPAY_CLIENT_ID=${PUSHPAY_CLIENT_ID}
      - PUSHPAY_CLIENT_SECRET=${PUSHPAY_CLIENT_SECRET}
      - PUSHPAY_MERCHANT_KEY=${PUSHPAY_MERCHANT_KEY}